version: '3.0.0'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      - REACT_APP_BACK_URL=
      - REACT_APP_S3_URL=
  
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    environment:
      - SESSION_KEY=
      - SPARCSSSO_CLIENT_ID=
      - SPARCSSSO_CLIENT_KEY=
      - FRONT_URL=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_S3_BUCKET_NAME=
      - DB_PATH=
      