version: '3.0.0'

networks:
  taxi-network:
    driver: bridge

services:
  nginx:
    container_name: taxi-nginx
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    depends_on:
      - client
      - server
    networks:
      - taxi-network

  client:
    container_name: taxi-client
    build: ./client
    environment:
      - REACT_APP_BACK_URL=${REACT_APP_BACK_URL}
      - REACT_APP_S3_URL=${REACT_APP_S3_URL}
    networks:
      - taxi-network

  server:
    container_name: taxi-server
    build: ./server
    environment:
      - SESSION_KEY=${SESSION_KEY}
      - SPARCSSSO_CLIENT_ID=${SPARCSSSO_CLIENT_ID}
      - SPARCSSSO_CLIENT_KEY=${SPARCSSSO_CLIENT_KEY}
      - FRONT_URL=${FRONT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}  
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - DB_PATH=${DB_PATH}
    networks:
      - taxi-network
  
  db:
    container_name: taxi-db
    image: mongo:4.4
    restart: always
    networks:
      - taxi-network
    